server:
  port: 9292

spring:
  # ===========================
  # Kafka Configuration
  # ===========================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: credit-risk-group
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'

springwolf:
  enabled: true
  plugin:
    kafka:
      publishing:
        enabled: true
        producer:
          bootstrap-servers:
            - localhost:9092
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  docket:
    base-package: com.deepak
    info:
      title: ${spring.application.name}
      version: 4.0
      description: loan service async communication
    servers:
      kafka-server:
        protocol: kafka
        host: localhost:9092
